[general]
live_config_reload      = true

[window]
startup_mode            = "Maximized"
opacity                 = 0.9

[font]
normal                  = { family = "0xProto Nerd Font Mono", style = "Regular" }
bold                    = { family = "0xProto Nerd Font Mono Bold", style = "Bold" }
italic                  = { family = "0xProto Nerd Font Mono Italic", style = "Italic" }

[cursor]
style                   = { shape = "block", blinking = "On" }
blink_interval          = 750

[terminal]
shell                   = { program = "wsl", args = ["-u", "voresan", "--cd", "~"] }

[keyboard]
bindings                = [{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }]
